project:
  type: website

website:
  title: "Economics"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/swadhin-mondal-12084713/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



